version: '2'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    user: "1000:50" # https://github.com/docker-library/mysql/issues/219
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: mysql@localhost
      MYSQL_DATABASE: janaf
      MYSQL_USER: janaf
      MYSQL_PASSWORD: password

  janaf-web:
    build: .
  development:
    image: y-ok/janaf-web
    container_name: janaf-web-development
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/janaf
      SPRING_DATASOURCE_USERNAME: janaf
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.jdbc.Driver
    links:
      - mysql

  product:
    image: y-ok/janaf-web
    container_name: janaf-web-product
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/janaf
      SPRING_DATASOURCE_USERNAME: janaf
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.jdbc.Driver
    links:
      - mysql
