spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/janaf
    username: janaf
    password: password
    driverClassName: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    cache: false
